### PR TITLE
Move to CSS modules + general changes

### PR DESCRIPTION
**Pull request by bluewave41**
- Moved to CSS modules

CSS modules come with the benefit of generated class names so there are no longer issues with reusing names eliminating the need for things like card2. Imports have changed from

`import './Header.css` to `import styles from './Header.css'`

And to use them instead of `className='header'` it's now `className={styles.header}`

- Added sass and classnames

Sass is a preprocessor for CSS. It's not required to use it but it allows for easier CSS. Most notably it's being used for nested dark mode components with the `&.dark` syntax to mean "if it has the parent x class and dark class"

Classnames comes with a `cn` import to combine multiple classes. cn(styles.header, styles.body) would give a tag with `<className='header body'>` and the second parameter handles conditional classes.

`cn(styles.header, { [styles.body]: 1 == 2 }` would only give <className='header'> because 1 is of course not 2 so we don't apply the body style.

- Broke out Card and Category buttons into their own components

- Created a ThemeProvider to handle dark mode

CSS modules are preferred in almost all cases but don't play well with the way styles were written before. This provider holds the current state and we could even initialize it with local storage to remember the users chosen style.

- Made categories heading white in dark mode
- Removed most inline styles in favour of stylesheets

Any files with less than ideal names were moved/renamed accordingly.

I also forgot to turn off my company styler so a lot of the changes are general indenting and replacing apostrophes with quotes. 😞 

97% of the changes are actually the package-lock which should be committed to the repo.

# Testing

- [ ] Checkout this PR (if you know how to do this great! If not [gh](https://github.com/cli/cli#installation) is a great tool for this. Just install it following their steps, open a terminal in your cloned repo and do `gh pr checkout 2`
- [ ] `npm install` to get dependencies
- [ ] Run the project with `npm run start`
- [ ] Play with the site ensuring it's functionally the same

Nothing should have changed besides minor card formatting, the Categories text turning white in dark mode and the header becoming more centered.

### CODE REVIEW

**Comment by danscarfe** [comment]
Amazing! Thanks so much! Not sure if I'm doing something wrong, but it wouldn't let me deploy to Azure:

image

**Comment by bluewave41** [comment]
> Amazing! Thanks so much! Not sure if I'm doing something wrong, but it wouldn't let me deploy to Azure:
> 
> image

Nope, good catch. The CategoryButtton import was still .css when it should've been .scss 😅

**Comment by MSmithDev** [comment]
Is this all set to merge?

**Comment by bluewave41** [comment]
Assuming someone has gone through and ensured it still looks mostly the same and functions properly it's a yes from me.

**Comment by danscarfe** [comment]
we're still trying to figure out why this new version won't deploy to Azure. We're now attempting to set up an action to auto-deploy it!

**Pull request merged**
